import Head from 'next/head'
import {useContext} from 'react'

import { TransactionContext } from '../context/TransactionContext'

export default function Home() {
  const { currentAccount } = useContext(TransactionContext)


  return (
    <div className=''>
      <Head>
        <title>FundRaiser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!currentAccount && <div className="h-screen overflow-hidden w-full flex justify-center items-center inset-0">
        <p className='font-bold text-6xl'>Please Login</p>
      </div>}

    </div>
  )
}
